name: CI

on:
    pull_request:

jobs:
    ci:
        runs-on: codeberg-tiny
        container: node:22
        steps:
            - uses: https://data.forgejo.org/actions/checkout@v4

            - name: Enable pnpm via corepack
              run: corepack enable

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run CI checks
              run: pnpm run ci
