import "roku_modules/rokurequests/Requests.brs"
import "config.bs"

function getVideoList(page as integer) as dynamic
    url = API_BASE + "/videos?page=" + page.ToStr()

    print "URL: "; url

    r = rokurequests_Requests().get(url)

    if r = invalid
        return invalid
    end if

    if not r.ok
        return invalid
    end if

    return r.json
end function

function submitWatch(id as string) as dynamic
    url = API_BASE + "/watch/" + id

    r = rokurequests_Requests().post(url, {})

    if r = invalid
        return invalid
    end if

    if not r.ok
        return invalid
    end if
    
    return r.json
end function

